# Generated by Django 4.2.5 on 2023-11-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('completed', 'completed')], default='assigned', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('maintenance_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.maintenanceperson')),
            ],
        ),
        migrations.CreateModel(
            name='FuelingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('completed', 'completed')], default='assigned', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fueling_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.fuelingperson')),
            ],
        ),
    ]
