# Generated by Django 4.2.5 on 2023-09-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_admin_user_alter_driver_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['name', 'surname']},
        ),
    ]
