# Generated by Django 4.2.5 on 2023-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driver_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelingperson',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='maintenanceperson',
            name='approved',
        ),
        migrations.AddField(
            model_name='fuelingperson',
            name='email',
            field=models.EmailField(default='example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelingperson',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fuelingperson',
            name='name',
            field=models.CharField(default='John', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelingperson',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fuelingperson',
            name='phone',
            field=models.CharField(default='898989', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelingperson',
            name='surname',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceperson',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceperson',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceperson',
            name='name',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceperson',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceperson',
            name='phone',
            field=models.CharField(default='234324', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceperson',
            name='surname',
            field=models.CharField(default='sdc', max_length=100),
            preserve_default=False,
        ),
    ]
