# Generated by Django 4.2.5 on 2023-11-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_fuelingtask_fueling_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelingTask',
        ),
    ]
