# Generated by Django 4.2.5 on 2023-10-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_fuelingperson_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/vehicle/')),
                ('date', models.DateField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.driver')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
