# Generated by Django 4.2.5 on 2023-11-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck'), ('Crossover', 'Crossover'), ('Van', 'Van'), ('Sports Car', 'Sports Car')], default='Sedan', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=15, verbose_name='Licence plate')),
                ('capacity', models.PositiveIntegerField(default=5, verbose_name='Sitting capacity')),
                ('mileage', models.FloatField(default=0, verbose_name='Mileage in km')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auction_vehicles/')),
                ('condition', models.TextField(default='')),
                ('additional_information', models.TextField(default='')),
            ],
            options={
                'ordering': ['-type', 'make', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly'), ('accidental', 'accidental')], default='scheduled', max_length=20)),
                ('type', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'completed')], default='monthly', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('maintenance_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='accounts.maintenanceperson')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('cost', models.PositiveBigIntegerField()),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_record', to='vehicles.maintenancejob')),
                ('maintenance_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='accounts.maintenanceperson')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck'), ('Crossover', 'Crossover'), ('Van', 'Van'), ('Sports Car', 'Sports Car')], default='Sedan', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=15, verbose_name='Licence plate')),
                ('capacity', models.PositiveIntegerField(verbose_name='Sitting capacity')),
                ('mileage', models.FloatField(default=0, verbose_name='Mileage in km')),
                ('status', models.CharField(choices=[('active', 'Active'), ('notactive', 'Not Active')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-type', 'make', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='VehicleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/vehicle/')),
                ('date', models.DateField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RepairingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_parts', to='vehicles.maintenancejob')),
            ],
        ),
        migrations.CreateModel(
            name='RepairedPartRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('part_photo', models.ImageField(blank=True, null=True, upload_to='maintenance_records/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repaired_parts', to='vehicles.maintenancerecord')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='maintenancejob',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_jobs', to='vehicles.vehicle'),
        ),
        migrations.CreateModel(
            name='FuelingProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_photo', models.ImageField(upload_to='fueling_records/', verbose_name='photo of the Driver')),
                ('image_before', models.ImageField(upload_to='fueling_records/', verbose_name='image before fueling')),
                ('image_after', models.ImageField(upload_to='fueling_records/', verbose_name='image after fueling')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('cost', models.PositiveIntegerField()),
                ('fueling_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fueling_proofs', to='accounts.fuelingperson')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fueling_proofs', to='vehicles.vehicle')),
            ],
        ),
    ]
