# Generated by Django 4.2.5 on 2023-11-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taks', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('completed', 'completed')], default='assigned', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fueling_tasks', to='vehicles.vehicle')),
            ],
        ),
    ]
