# Generated by Django 4.2.5 on 2023-11-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_fuelingtask'),
        ('vehicles', '0002_fuelingtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelingproof',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='fuelingtask',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='fuelingtask',
            old_name='taks',
            new_name='tasK',
        ),
        migrations.AlterField(
            model_name='fuelingproof',
            name='fueling_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fueling_proofs', to='accounts.fuelingperson'),
        ),
    ]
