# Generated by Django 4.2.5 on 2023-10-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelingProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_before', models.ImageField(upload_to='fueling_records/', verbose_name='image before fueling')),
                ('image_after', models.ImageField(upload_to='fueling_records/', verbose_name='image after fueling')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.RemoveField(
            model_name='fuelingrecord',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='FuelingInfo',
        ),
        migrations.DeleteModel(
            name='FuelingRecord',
        ),
    ]
