# Generated by Django 4.2.5 on 2023-10-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_fuelingproof_remove_fuelingrecord_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelingproof',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
