# Generated by Django 4.2.5 on 2023-10-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_fuelingperson_approved_and_more'),
        ('vehicles', '0004_alter_fuelingproof_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelingproof',
            name='fueling_person',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), to='accounts.fuelingperson'),
            preserve_default=False,
        ),
    ]
