# Generated by Django 4.2.5 on 2023-11-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_rename_task_fuelingtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelingproof',
            name='driver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fueling_records/', verbose_name='photo of the Driver'),
        ),
        migrations.AlterField(
            model_name='fuelingproof',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='fueling_records/', verbose_name='image after fueling'),
        ),
        migrations.AlterField(
            model_name='fuelingproof',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to='fueling_records/', verbose_name='image before fueling'),
        ),
    ]
