# Generated by Django 4.2.5 on 2023-10-05 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_fuelingperson_approved_and_more'),
        ('vehicles', '0005_fuelingproof_fueling_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancejob',
            name='maintenance_person',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='maintenance_jobs', to='accounts.maintenanceperson'),
        ),
        migrations.AddField(
            model_name='maintenancejob',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'completed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_person',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='maintenance_records', to='accounts.maintenanceperson'),
        ),
        migrations.AlterField(
            model_name='fuelingproof',
            name='fueling_person',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='fueling_proofs', to='accounts.fuelingperson'),
        ),
        migrations.AlterField(
            model_name='fuelingproof',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fueling_proofs', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='maintenancejob',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_jobs', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle'),
        ),
    ]
