# Generated by Django 4.2.5 on 2023-10-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_maintenancejob_maintenance_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancejob',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelingproof',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenancejob',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='completed_on',
            field=models.DateTimeField(),
        ),
    ]
