# Generated by Django 4.2.5 on 2023-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_maintenancejob_description_alter_fuelingproof_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notactive', 'Not Active')], default='active', max_length=20),
        ),
    ]
