# Generated by Django 4.2.5 on 2023-10-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='completed_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='replaced_part_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='replaced_part_photo',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_records/'),
        ),
        migrations.CreateModel(
            name='VehicleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/vehicle/')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vehicles.vehicle')),
            ],
        ),
    ]
