# Generated by Django 4.2.5 on 2023-10-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_maintenancerecord_completed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='completed_on',
            field=models.DateField(),
        ),
    ]
