# Generated by Django 4.2.5 on 2023-10-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_maintenancerecord_completed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='completed_on',
            new_name='date',
        ),
    ]
