# Generated by Django 4.2.5 on 2023-10-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_rename_completed_on_maintenancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelingproof',
            name='amount',
            field=models.FloatField(),
        ),
    ]
