# Generated by Django 4.2.5 on 2023-10-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_fuelingproof_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelingproof',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
