# Generated by Django 4.2.5 on 2023-10-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_fuelingproof_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.FloatField(default=0, verbose_name='Mileage in km'),
        ),
    ]
