# Generated by Django 4.2.5 on 2023-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_alter_vehicle_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclereport',
            name='date',
            field=models.DateField(default='2023-10-17'),
            preserve_default=False,
        ),
    ]
