# Generated by Django 4.2.5 on 2023-10-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_alter_vehiclereport_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclereport',
            options={'ordering': ['-date']},
        ),
    ]
