# Generated by Django 4.2.5 on 2023-10-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_alter_vehiclereport_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='license_plat',
            new_name='license_plate',
        ),
    ]
