# Generated by Django 4.2.5 on 2023-10-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_rename_license_plat_vehicle_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelingproof',
            name='driver_photo',
            field=models.ImageField(default='fueling_records/download.jpeg', upload_to='fueling_records/', verbose_name='photo of the Driver'),
            preserve_default=False,
        ),
    ]
