# Generated by Django 4.2.5 on 2023-10-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driverreport'),
        ('vehicles', '0020_alter_auctionvehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelingproof',
            name='fueling_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fueling_proofs', to='accounts.fuelingperson'),
        ),
        migrations.AlterField(
            model_name='maintenancejob',
            name='maintenance_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_jobs', to='accounts.maintenanceperson'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='accounts.maintenanceperson'),
        ),
    ]
