# Generated by Django 4.2.5 on 2023-10-31 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driverreport'),
        ('vehicles', '0021_alter_fuelingproof_fueling_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancejob',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='replaced_part_number',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='replaced_part_photo',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='service_type',
        ),
        migrations.AddField(
            model_name='maintenancejob',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-13 14:48:06+06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancejob',
            name='type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'completed')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed_on',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-13 14:48:06+06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancejob',
            name='maintenance_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='accounts.maintenanceperson'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='accounts.maintenanceperson'),
        ),
        migrations.CreateModel(
            name='ReplacedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, null=True)),
                ('part_photo', models.ImageField(blank=True, null=True, upload_to='maintenance_records/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_parts', to='vehicles.maintenancerecord')),
            ],
        ),
        migrations.CreateModel(
            name='RepairingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_parts', to='vehicles.maintenancejob')),
            ],
        ),
    ]
