# Generated by Django 4.2.5 on 2023-11-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0025_rename_repairedpart_repairedpartrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancejob',
            name='status',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly'), ('accidental', 'accidental')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=models.PositiveBigIntegerField(),
        ),
    ]
