# Generated by Django 4.2.5 on 2023-11-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('from_point', models.CharField(max_length=200, verbose_name='departure point')),
                ('to_point', models.CharField(max_length=200, verbose_name='arrival point')),
                ('time_from', models.DateTimeField(blank=True, null=True)),
                ('time_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Assigned', max_length=20)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_task', to='vehicles.vehicle')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.driver')),
            ],
            options={
                'ordering': ['time_from'],
            },
        ),
        migrations.CreateModel(
            name='CompletedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.JSONField(verbose_name='departure point')),
                ('to_point', models.JSONField(verbose_name='arrival point')),
                ('time_from', models.DateTimeField(blank=True, null=True)),
                ('time_to', models.DateTimeField(blank=True, null=True)),
                ('distance_covered', models.FloatField()),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='accounts.driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_routes', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-time_from'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPosition', models.CharField(default='', max_length=100)),
                ('destination', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck'), ('Crossover', 'Crossover'), ('Van', 'Van'), ('Sports Car', 'Sports Car')], default='Sedan', max_length=20)),
                ('time_from', models.DateTimeField(blank=True, null=True)),
                ('time_to', models.DateTimeField(blank=True, null=True)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('additionalInfo', models.CharField(default='', max_length=100)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.driver')),
            ],
            options={
                'ordering': ['-time_from'],
            },
        ),
    ]
