# Generated by Django 4.2.5 on 2023-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedroute',
            name='distance_covered',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='completedroute',
            name='from_point',
            field=models.CharField(max_length=200, verbose_name='departure point'),
        ),
        migrations.AlterField(
            model_name='completedroute',
            name='to_point',
            field=models.CharField(max_length=200, verbose_name='arrival point'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Canceled', 'Canceled')], default='Assigned', max_length=20),
        ),
    ]
