# Generated by Django 4.2.5 on 2023-09-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_appointment_date_appointment_time_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['time_from']},
        ),
        migrations.AlterModelOptions(
            name='completedroutes',
            options={'ordering': ['-time_from']},
        ),
        migrations.RemoveField(
            model_name='completedroutes',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='currentPosition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='completedroutes',
            name='time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedroutes',
            name='time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
