# Generated by Django 4.2.5 on 2023-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additionalInfo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
