# Generated by Django 4.2.5 on 2023-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_appointment_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
