# Generated by Django 4.2.5 on 2023-09-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_appointment_number_of_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedroutes',
            name='task_id',
        ),
    ]
