# Generated by Django 4.2.5 on 2023-09-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_completedroutes_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedroutes',
            name='distance_covered',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='completedroutes',
            name='time_spent',
            field=models.CharField(default=''),
        ),
    ]
