# Generated by Django 4.2.5 on 2023-10-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_fuelingperson_approved_and_more'),
        ('tasks', '0008_alter_completedroutes_distance_covered_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedRoutes',
            new_name='CompletedRoute',
        ),
    ]
