# Generated by Django 4.2.5 on 2023-10-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_fuelingproof_cost'),
        ('tasks', '0009_rename_completedroutes_completedroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedroute',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_routes', to='vehicles.vehicle'),
        ),
    ]
