# Generated by Django 4.2.5 on 2023-10-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_completedroute_distance_covered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedroute',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
