# Generated by Django 4.2.5 on 2023-09-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_admin_user_alter_driver_user_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.JSONField(verbose_name='departure point')),
                ('to_point', models.JSONField(verbose_name='arrival point')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Assigned', max_length=20)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_task', to='vehicles.vehicle')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.driver')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CompletedRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.JSONField(verbose_name='departure point')),
                ('to_point', models.JSONField(verbose_name='arrival point')),
                ('date', models.DateTimeField()),
                ('distance_covered', models.CharField()),
                ('time_spent', models.CharField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='accounts.driver')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck'), ('Crossover', 'Crossover'), ('Van', 'Van'), ('Sports Car', 'Sports Car')], default='Sedan', max_length=20)),
                ('date', models.DateTimeField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.driver')),
            ],
        ),
    ]
