# Generated by Django 4.2.5 on 2023-09-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_vehicles/')),
                ('status', models.CharField()),
                ('cost', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck'), ('Crossover', 'Crossover'), ('Van', 'Van'), ('Sports Car', 'Sports Car')], default='Sedan', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('license_plat', models.CharField(max_length=15, verbose_name='Licence plate')),
                ('capacity', models.PositiveIntegerField(verbose_name='Sitting capacity')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Mileage in km')),
            ],
            options={
                'ordering': ['-type', 'make', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('replaced_part_number', models.CharField()),
                ('replaced_part_photo', models.ImageField(upload_to='maintenance_records/')),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_photo', models.ImageField(upload_to='fueling_records/', verbose_name='Mileage photo')),
                ('mileage_photo', models.ImageField(upload_to='fueling_records/', verbose_name='Driver photo')),
                ('image_before', models.ImageField(upload_to='fueling_records/', verbose_name='image before fueling')),
                ('image_after', models.ImageField(upload_to='fueling_records/', verbose_name='image after fueling')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelType', models.CharField(max_length=100)),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
